<a href="https://colab.research.google.com/github/salemprakash/testing/blob/master/Firstnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
np.array([2,4,6,2,52,5,6,True])

array([ 2,  4,  6,  2, 52,  5,  6,  1])

In [10]:
np.arange(111,11,-1)

array([111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,
        98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,
        85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,
        72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,
        59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,
        46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,
        33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,
        20,  19,  18,  17,  16,  15,  14,  13,  12])

In [12]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [16]:
np.linspace(1,10, num=30, retstep =True)

(array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
         2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
         4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
         5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
         7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
         8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ]),
 0.3103448275862069)

In [17]:
np.random.randint(1,10)

7

In [18]:
np.random.randint(1,10, 5)

array([5, 2, 8, 1, 4])

In [29]:
np.random.randint(1,10, (5,5))

array([[4, 8, 8, 5, 6],
       [4, 7, 9, 1, 3],
       [8, 8, 8, 4, 1],
       [9, 8, 8, 2, 2],
       [4, 1, 9, 7, 5]])

In [23]:
x = np.random.randint(1,10, (5,5))
x

array([[1, 7, 2, 2, 3],
       [8, 1, 2, 8, 8],
       [8, 8, 5, 3, 5],
       [6, 8, 1, 3, 7],
       [5, 7, 3, 4, 6]])

In [24]:
x[0]

array([1, 7, 2, 2, 3])

In [30]:
np.random.seed(1)
np.random.randint(1,10, (5,5))

array([[6, 9, 6, 1, 1],
       [2, 8, 7, 3, 5],
       [6, 3, 5, 3, 5],
       [8, 8, 2, 8, 1],
       [7, 8, 7, 2, 1]])